Fix scudo_test.c for clang update
After clang update, we get below error:

trusty/user/base/lib/scudo/test/scudo_test.c:108:20: error:
a function declaration without a prototype is deprecated in
all versions of C [-Werror,-Wstrict-prototypes]
static bool has_mte() {
                   ^
                    void

Bug: 251888886
Test: run trusty/vendor/google/aosp/scripts/build.py
Change-Id: I099f9da8677328d77f74ded935e7038070373d4e